### ISSUE TITLE
Doesn't work with the latest Xenus version [0.19]

### ISSUE THREAD

**Issue by opeadeyomoye** [abellion/xenus-laravel#2]
Hi @abellion, thanks a ton for your work on Xenus.

I just tried installing `xenus-laravel` and it looks to have some compatibility issues with the [most recent release (0.19)](https://github.com/abellion/xenus/releases/tag/0.19) of Xenus which brings in support for php 8.1.

I'm running php8.1 locally and here's the "require" portion of my `composer.json`:
```json
    "require": {
        "php": "^8.1",
        "abellion/xenus": "0.19",
        "laravel/lumen-framework": "^9.0",
        "mongodb/mongodb": "1.11.0"
    },
```
Currently, when I try running:
```bash
composer require abellion/xenus-laravel:0.3
```
this is the output:
```bash
./composer.json has been updated
Running composer update abellion/xenus-laravel
Loading composer repositories with package information
Info from https://repo.packagist.org: #StandWithUkraine
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires abellion/xenus-laravel 0.3 -> satisfiable by abellion/xenus-laravel[0.3].
    - abellion/xenus-laravel 0.3 requires abellion/xenus ^0.18.0 -> found abellion/xenus[0.18] but it conflicts with your root composer.json require (0.19).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

Looks like it's caused by [this line](https://github.com/abellion/xenus-laravel/blob/934182f9340635f78e4730b5ff8a58162c5ef9cf/composer.json#L9) in `xenus-laravel`'s dependency list that restricts the acceptable Xenus versions to the `0.18.x` range. Do you think we can safely expand this range to include Xenus 0.19.x?

**Comment by abellion** [comment]
Hello,

> Do you think we can safely expand this range to include Xenus 0.19.x?

Yes, since the 0.19 version only adds support for PHP 8.1, this shouldn't cause any issue :)

**Comment by opeadeyomoye** [comment]
Great.

Is it okay to send in a PR to that effect then?

**Comment by abellion** [comment]
I've been a bit quicker unfortunately ! Changes are implemented in master. Can you try and tell me if everything works as expected ? (https://packagist.org/packages/abellion/xenus-laravel#dev-master)

**Comment by opeadeyomoye** [comment]
Install works now 👍🏾 .  I ran:
```bash
composer require abellion/xenus-laravel:dev-master
```
All that's left might be to tag a release.

Great work. Thanks!

**Comment by abellion** [comment]
Done ✅
